name: Test CI

on: [push]  # Se ejecuta cada vez que hagas un push al repositorio

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a test script
        run: echo "✅ GitHub Actions está funcionando correctamente"
# This is a basic workflow to help you get started with Actions


        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
